{"content": {"suites": {"0": {"status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_all_project_info", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_project_info_models", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_project_users_models", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_file_upload", "rerun": "0"}, "4": {"status": "ERROR", "message": "setup_projectusers = []\n\n    @pytest.fixture\n    def setup_project_activitylog(setup_projectusers):\n    \n    \tactivity_logs=[]\n    \tfor projectuser in ProjectUsers.objects.all():\n    \t\tactivity={\"project_user\":projectuser,\"timestamp\":fake.date()\n>   \t\t\t,\"activity\":fake.text(max_nb_char=100),\"ip_address\":fake.ipv4(),\"created_by_id\":1}\nE     TypeError: text() got an unexpected keyword argument 'max_nb_char'\n\nconftest.py:800: TypeError\n", "test_name": "test_activity_logs", "rerun": "0"}}, "suite_name": "project/Test_project/test_models.py"}}}, "date": "August 30, 2021", "start_time": 1630327339.164613, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "4", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}