{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 8}, "tests": {"0": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDED28148>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '13a600fc-893b-4fc9-bc79-06d0caef076e', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDED28148>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDED2EB88>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '13a600fc-893b-4fc9-bc79-06d0caef076e', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDED2EB88>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '13a600fc-893b-4fc9-bc79-06d0caef076e', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser1@momenttext.com-3-5-Company-Management]", "rerun": "0"}, "1": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDD896988>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '151fc772-93a6-4158-8e04-dd8f5471b225', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDD896988>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD8CFDC8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '151fc772-93a6-4158-8e04-dd8f5471b225', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD8CFDC8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '151fc772-93a6-4158-8e04-dd8f5471b225', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser1@momenttext.com-3-5-Project-Management]", "rerun": "0"}, "2": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDD8D0748>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '726617f6-5c47-42ff-b097-a117ebe0da08', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDD8D0748>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD879DC8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '726617f6-5c47-42ff-b097-a117ebe0da08', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD879DC8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '726617f6-5c47-42ff-b097-a117ebe0da08', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser2@momenttext.com-3-5-Company-Management]", "rerun": "0"}, "3": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDEA88108>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26354ca7-3e97-41b4-baf9-8fb3c7f9c9f3', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDEA88108>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDED2E798>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26354ca7-3e97-41b4-baf9-8fb3c7f9c9f3', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDED2E798>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26354ca7-3e97-41b4-baf9-8fb3c7f9c9f3', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser2@momenttext.com-3-5-Project-Management]", "rerun": "0"}, "4": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDE9C8508>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', 'c52687b7-4c43-4dd3-bf08-573c0c0a140c', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDE9C8508>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD8799D8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', 'c52687b7-4c43-4dd3-bf08-573c0c0a140c', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDD8799D8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', 'c52687b7-4c43-4dd3-bf08-573c0c0a140c', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser4@momenttext.com-3-5-Company-Management]", "rerun": "0"}, "5": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDD8E4388>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '7a85bde2-7870-437f-820c-e1b3581133cc', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDD8E4388>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEA66438>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '7a85bde2-7870-437f-820c-e1b3581133cc', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEA66438>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '7a85bde2-7870-437f-820c-e1b3581133cc', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser4@momenttext.com-3-5-Project-Management]", "rerun": "0"}, "6": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDEC23188>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26f12d38-a077-41d7-9f6d-57143764bd89', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDEC23188>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEA663A8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26f12d38-a077-41d7-9f6d-57143764bd89', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEA663A8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '26f12d38-a077-41d7-9f6d-57143764bd89', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser5@momenttext.com-3-5-Company-Management]", "rerun": "0"}, "7": {"status": "ERROR", "message": "self = <django.db.backends.utils.CursorWrapper object at 0x0000014BDEB58908>\nsql = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '58c95544-8579-408f-a19c-86a0ac3c7cf7', ...]\nignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x0000014BDCF75C48>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x0000014BDEB58908>})\n\n    def _execute(self, sql, params, *ignored_wrapper_args):\n        self.db.validate_no_broken_transaction()\n        with self.db.wrap_database_errors:\n            if params is None:\n                # params default might be backend specific.\n                return self.cursor.execute(sql)\n            else:\n>               return self.cursor.execute(sql, params)\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEE4E8B8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '58c95544-8579-408f-a19c-86a0ac3c7cf7', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       sqlite3.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def setup_saved_user():\n    \tusers=[\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser1@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user2\",\"email\":\"testuser2@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user3\",\"email\":\"testuser3@momenttext.com\",\"active\":True\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t},\n    \t\t{\"first_name\":\"test\",\"last_name\":\"user4\",\"email\":\"testuser4@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user5\",\"email\":\"testuser5@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user6\",\"email\":\"testuser6@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":True,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser7@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t\t,{\"first_name\":\"test\",\"last_name\":\"user1\",\"email\":\"testuser8@momenttext.com\",\"active\":False\n    \t\t,\"user_verified\":False,\"password\":generate_passwords(\"Password@123\"),\"token\":fake.uuid4()\n    \t\t   ,\"hashkey\":fake.uuid4()[:10],\n    \t\t}\n    \t]\n    \totp=\"\"\n    \tfor obj in users:\n>   \t\tgetUsers=Users.objects.create(**obj)\n\n..\\..\\conftest.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:453: in create\n    obj.save(force_insert=True, using=self.db)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:727: in save\n    force_update=force_update, update_fields=update_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:765: in save_base\n    force_update, using, update_fields,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:868: in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\base.py:908: in _do_insert\n    using=using, raw=raw,\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\manager.py:85: in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\query.py:1270: in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\models\\sql\\compiler.py:1416: in execute_sql\n    cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:66: in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:75: in _execute_with_wrappers\n    return executor(sql, params, many, context)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\utils.py:90: in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\utils.py:84: in _execute\n    return self.cursor.execute(sql, params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000014BDEE4E8B8>\nquery = 'INSERT INTO \"Users\" (\"first_name\", \"last_name\", \"name\", \"email\", \"password\", \"token\", \"designation\", \"active\", \"user_...porting_manager_email\", \"hashkey\", \"created_at\", \"updated_at\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'\nparams = ['test', 'user1', None, 'testuser1@momenttext.com', '8c8dc5ced8f13d767526c4621e060f8e1eb8872ada3be5ca984f8b1ae478917f', '58c95544-8579-408f-a19c-86a0ac3c7cf7', ...]\n\n    def execute(self, query, params=None):\n        if params is None:\n            return Database.Cursor.execute(self, query)\n        query = self.convert_query(query)\n>       return Database.Cursor.execute(self, query, params)\nE       django.db.utils.IntegrityError: UNIQUE constraint failed: Users.email\n\n..\\..\\..\\mmtxt\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py:423: IntegrityError\n", "test_name": "test_create_usercompanyrole[testuser5@momenttext.com-3-5-Project-Management]", "rerun": "0"}}, "suite_name": "organization/Test_organization/test_views.py"}}}, "date": "August 30, 2021", "start_time": 1630308534.8842824, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "8", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}