{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "               django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: accessmanagement, active, activitylogs, company_created_by, company_updated_by, companyinfo_created_by, companyinfo_updated_by, created_at, designation, email, expiry_date, fileupload, first_name, getprogress, hashkey, id, last_name, name, password, project_created_by, project_updated_by, project_user_created_by, project_user_updated_by, reporting_manager_email, reporting_manager_id, reporting_manager_name, role_created_by, role_updated_by, temporaryurl, token, updated_at, user_role_created_by, user_role_updated_by, user_verified, usercompanyrole\n", "test_name": "test_temporary_url", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_models.py"}}}, "date": "August 18, 2021", "start_time": 1629276177.1130686, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}