{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "setup_saved_user = [{'active': True, 'email': 'testuser1@kpmg.com', 'first_name': 'test', 'hashkey': '01a17620-f', ...}, {'active': True,...9f-e', ...}, {'active': False, 'email': 'testuser6@kpmg.com', 'first_name': 'test', 'hashkey': '3e4573d5-a', ...}, ...]\nsetup_random_user = [{'active': True, 'email': 'testuser1@kpmg.com', 'first_name': 'test', 'hashkey': '09cae64e-b', ...}, {'active': True,...55-c', ...}, {'active': False, 'email': 'testuser6@kpmg.com', 'first_name': 'test', 'hashkey': '4212218d-7', ...}, ...]\n\n    @pytest.fixture\n    def setup_temporary_urls(setup_saved_user,setup_random_user):\n    \tusers=setup_random_user\n    \n    \tfor x in range(1,len(users)+1):\n    \t\tgetUser=Users.objects.get(email__iexact=users[x][\"email\"])\n    \t\ttemporary_url={\"user\":getUser\n                    ,\"token\":getUser.token\n                    ,\"filename\":fake.file_name(category=\"file\",extension=\"xlsx\")\n                    ,\"filepath\":fake.file_path(depth=2,category=\"file\",extension=\"xlsx\")\n>   \t\t\t\t,\"expiry_time\":datetime.datetime.now()\n                    }\nE     AttributeError: type object 'datetime.datetime' has no attribute 'datetime'\n\n..\\..\\conftest.py:207: AttributeError\n", "test_name": "test_temporary_url", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_models.py"}}}, "date": "August 18, 2021", "start_time": 1629271696.1982543, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}